### ISSUE TITLE
Unable to obtain model pretrained parameters.

### ISSUE THREAD

**Issue by kolyapple** [Sam1224/SCCAN#3]
Hello, I encountered some issues during the process of reproducing the experiment. The pre trained parameters need to be obtained through application. I hope to address this issue once I see it. Thank you for your contribution!

**Comment by Sam1224** [comment]
Hello, thanks for your interests in our work, and thanks for pointing out this issue. I just checked that there were some problems with the originally Google Drive account, and I have uploaded the files to my OneDrive. You can download the initmodels and all pretrained models now.

**Comment by kolyapple** [comment]
Thank you!
